swipe:
  3: 
    left: 
      command: 'xdotool key alt+Left'
    right: 
      command: 'xdotool key alt+Right'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super'
  4:
    up:
      command: 'xdotool key Ctrl+Super+Up'
    down:
      command: 'xdotool key ctrl+Super+Down'
